//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCPLWebEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExternalLeague
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ExternalLeague()
        {
            this.Player_External = new HashSet<Player_External>();
            this.SpecialEvent_ExternalLeague = new HashSet<SpecialEvent_ExternalLeague>();
        }
    
        public int ExternalLeagueId { get; set; }
        public string ExternalLeagueName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player_External> Player_External { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialEvent_ExternalLeague> SpecialEvent_ExternalLeague { get; set; }
    }
}
