//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCPLWebEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecialEvent
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SpecialEvent()
        {
            this.Player_SpecialEvent = new HashSet<Player_SpecialEvent>();
            this.SpecialEvent_ExternalLeague = new HashSet<SpecialEvent_ExternalLeague>();
        }
    
        public int SpecialEventId { get; set; }
        public string EventName { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime EndDate { get; set; }
        public bool EntryFeeYN { get; set; }
        public Nullable<decimal> EntryFeeAmount { get; set; }
        public Nullable<decimal> EntryFeeAmountOnline { get; set; }
        public bool RegistrationRequiredYN { get; set; }
        public Nullable<System.DateTime> RegistrationStartDate { get; set; }
        public Nullable<System.DateTime> RegistrationEndDate { get; set; }
        public string CustomPageURL { get; set; }
        public System.DateTime CreateDateTime { get; set; }
        public bool MultiLeagueEventYN { get; set; }
        public string EventSubtitle { get; set; }
        public string EventDesc { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Player_SpecialEvent> Player_SpecialEvent { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SpecialEvent_ExternalLeague> SpecialEvent_ExternalLeague { get; set; }
    }
}
