//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCPLWebEntities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class wcplDbEntities : DbContext
    {
        public wcplDbEntities()
            : base("name=wcplDbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ExternalLeague> ExternalLeagues { get; set; }
        public virtual DbSet<Player> Players { get; set; }
        public virtual DbSet<Player_External> Player_External { get; set; }
        public virtual DbSet<Player_SpecialEvent> Player_SpecialEvent { get; set; }
        public virtual DbSet<SpecialEvent> SpecialEvents { get; set; }
        public virtual DbSet<SpecialEvent_ExternalLeague> SpecialEvent_ExternalLeague { get; set; }
    }
}
